---
- name: Deploy rgbdn
  hosts: all
  become: false
  gather_facts: false

  vars:
    deploy_dir: /home/pi/rgbdn

  tasks:
    - name: Install pip
      ansible.builtin.package:
        name: python3-pip
      become: true

    - name: Copy binaries
      ansible.posix.synchronize:
        src: ./
        dest: "{{ deploy_dir }}"
      notify: Restart service

    - name: Install pip packages # noqa: package-latest - we want latest and greatest
      ansible.builtin.pip:
        requirements: "{{ deploy_dir }}/requirements.txt"
        state: latest
      tags: teee

    - name: Install service file
      ansible.builtin.copy:
        src: "{{ deploy_dir }}/rgbdn.service"
        dest: ~/.config/systemd/user/rgbdn.service
        remote_src: true
        mode: "0644"
        owner: pi
        group: pi
      register: copy
      tags: service
      notify: Restart service

    - name: Enable and start service
      ansible.builtin.systemd:
        daemon_reload: "{{ copy.changed }}"
        name: rgbdn
        enabled: true
        scope: user
        state: started
      tags: service

  handlers:
    - name: Restart service
      ansible.builtin.systemd:
        name: rgbdn
        scope: user
        state: restarted
